### ISSUE TITLE
Your plugin may be breaking recent Etherpad versions

### ISSUE THREAD

**Issue by shiva2020** [ldidry/ep_delete_after_delay#1]
Hello,

I am trying to get your plugin up and running in Etherpad. It seems to fail on Ubuntu 14.04/Etherpad latest on develop branch as well as on locked release/1.6.1 tag (latest release). I built Node.js from source as per their documentation. I installed your plugin with the Etherpad admin plugins panel, used the same settings as your defaults for the settings.json. It causes no pads (new or existing) to load, with output like this instead of pad-edit pages: http://i.imgur.com/7AnrnNO.png

My settings.json has a section like this:

```
  "ep_delete_after_delay": {
    "delay": 86400,
    "loop": true,
    "loopDelay": 3600,
    "deleteAtStart": true,
    "text": "The content of this pad has been deleted since it was older than the configured deletion delay."
  }
```

near the end. I've checked 10 times that the syntax should be good, there are no complaints from the plugin about unset values when the blocks is in settings.json, and no errors or warnings in console output.

Can you look into this, I really need delete after delay functionality and I spent like 5 hours on this tonight looking at permissions and trying to figure out Javascript etc.

The output on the Etherpad page where the pad should be suggests it's not happy about something on the line "'path': exports.baseURL + "socket.io"," in this block:

```
function handshake()
{
  var loc = document.location;
  //get the correct port
  var port = loc.port == "" ? (loc.protocol == "https:" ? 443 : 80) : loc.port;
  //create the url
  var url = loc.protocol + "//" + loc.hostname + ":" + port + "/";
  //find out in which subfolder we are
  var resource =  exports.baseURL.substring(1)  + "socket.io";
  //connect
  socket = pad.socket = io.connect(url, {
    // Allow deployers to host Etherpad on a non-root path
    'path': exports.baseURL + "socket.io",
    'resource': resource,
    'reconnectionAttempts': 5,
    'reconnection' : true,
    'reconnectionDelay' : 1000,
    'reconnectionDelayMax' : 5000
  });
```

Thanks for any help. I also have the ep_push2delete plugin installed, which seems to work fine when your plugin is not installed.

**Comment by ldidry** [comment]
I just published a new version that seems to fix the bug. Will be available on `admin/plugins` interface in a few hours, or right now on npm.
